### ISSUE TITLE
Suggestion: Game Review Overview

### ISSUE THREAD

**Issue by timweissenfels** [WintrCat/freechess#15]
Hey, thanks for creating this!

Don't know how much effort it is, but maybe you could think about adding the typical Overview from Chess.com that sums up all the moves and compares them to your opponent.

![image](https://github.com/WintrCat/freechess/assets/32968964/8b67e956-dad2-4d11-a5f9-eb01fd97d8db)

**Comment by WintrCat** [comment]
This would not fit in the sidebar as is which means it would require an overhaul of the UI to get this done, so I don't plan on adding it, unless someone else can contribute such UI changes 👍
