### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by stefnotch** [WintrCat/freechess#20]
So after looking at this project again, I noticed something rather annoying.

It uses ReCaptcha, which is apparently not GDPR compliant. Which I'd argue is a big issue, because it's a legal issue.
(In the UK, the closest GDPR equivalent is supposedly Data Protection, Privacy and Electronic Communication, but I'm really not a lawyer.)

As for fixing that, there are 3 avenues that I'm aware of
- Removing the captcha. That opens up the backend to spamming, so not cool.
- FriendlyCaptcha. It's a GDPR compliant alternative.
- Moving the backend logic to the frontend, and thus getting rid of the backend #14 . I'd also happily assist with this and with any merge conflicts that might pop up.

**Comment by WintrCat** [comment]
i will need to add a privacy policy and maybe a cookie banner to comply with GDPR 👍

**Comment by stefnotch** [comment]
Sounds good, thanks for caring about this :D
