### ISSUE TITLE
reCaptcha problem

### ISSUE THREAD

**Issue by tissatussa** [WintrCat/freechess#45]
i really like your analyses tool ! i used it on http://chess.wintrcat.uk and i also compiled your freechess source to run on my localhost.

however, after the analyses of a PGN game, a reCaptcha element appears and i'm not able to remove / solve it .. i also went to the concerning Google webpage to register my localhost (127.0.0.1), which seems to work, but after using the secret keys as you describe, the problem remains ..

i can do some coding, so how to solve this ?
can't we just skip the whole captcha thing ?

you should definitely continue this project .. i encountered a few alternative applications (not web based) but to me they all have their shortcomings .. you interface is simple and clear !

[ i'm on Xubuntu 22.4 ]

**Comment by WintrCat** [comment]
Hi mate, you can use a fork of the freechess repository with no ReCAPTCHA (as well as a couple otehr bits that make it easier for people wanting to host locally)
https://github.com/Theohaines/freechessextra

It's maintained by one of my friends and he updates it as often as he can :)

**Comment by tissatussa** [comment]
nice .. and it works !

i will post any remarks and questions there .. thank you.
