### ISSUE TITLE
how to display JSON Result data ?

### ISSUE THREAD

**Issue by tissatussa** [WintrCat/freechess#46]
after an analysis is done, clicking the 'save' botton (in the bottom right corner) brings up a new window with the results in JSON format. That's very nice, but this data format isn't readable for a normal user .. shall i write a script which converts this into a readable list ? In Python or JS.

**Comment by WintrCat** [comment]
On many browsers you can turn on Pretty Print to see a formatted version. Although, the report savefile doesn't really need to be readable for the user, since you can simply load it back into Game Report using load game by JSON.
