### ISSUE TITLE
Obvious blunder wasn't recognized

### ISSUE THREAD

**Issue by LevaniVashadze** [WintrCat/freechess#6]
![Screenshot_20240211_225909_Firefox.jpg](https://github.com/WintrCat/freechess/assets/100613979/0dbf413a-0b62-4f21-ae9e-9b9dc2d6c3c0)

blob:https://chess.wintrcat.uk/cfe74a06-addb-4d40-b48e-3f27d263327f

I blundered my queen and my move still got classified as 'good'. 

Great work on the website regardless.

**Comment by WintrCat** [comment]
Hey Levani - could you send me the PGN that you analysed and the search depth you used? I'll have a look at it for myself.

**Comment by LevaniVashadze** [comment]
[Event "levani_13 vs. MICRORAHUL"]
[Site "Chess.com"]
[Date "2024-02-11"]
[White "levani_13"]
[Black "MICRORAHUL"]
[Result "0-1"]
[WhiteElo "499"]
[BlackElo "520"]
[TimeControl "600"]
[Termination "MICRORAHUL won by checkmate"]
1. d4 d5 2. Bf4 Nc6 3. e3 e6 4. Bb5 Bb4+ 5. c3 Be7 6. Qh5 Nf6 7. Qg5 h6 8. Qxg7
Rg8 9. Qxh6 Bf8 10. Qh3 e5 11. Bxe5 Bxh3 12. gxh3 Nd7 13. Nf3 a6 14. Bxc6 bxc6
15. Nbd2 c5 16. O-O-O Qc8 17. Rdg1 Rxg1+ 18. Rxg1 Qb7 19. b4 cxb4 20. cxb4 Rb8
21. a3 f6 22. Bf4 Qc6+ 23. Kd1 Qa4+ 24. Ke2 Qxa3 25. Rg8 Qxb4 26. Bxc7 Rc8 27.
Bf4 Kf7 28. Rg4 a5 29. Nh4 a4 30. Nf5 a3 31. Rg7+ Bxg7 32. Bd6 Qb5+ 33. Kf3 a2
34. Ne7 a1=Q 35. Nxc8 Qd1+ 36. Kf4 Qxd2 37. Ne7 Qxf2+ 38. Kg4 Qbe2# 0-1

**Comment by LevaniVashadze** [comment]
I reviewes the game on chess.com and got this. It marks the move before the loss of the queen a blunder but the move while the queen is getting captured is marke as good. So i understand why the website categorized it as it did. https://www.chess.com/live/game/101250757290

**Comment by WintrCat** [comment]
The evaluation was -3.5 and then -5 after white hung the queen; at least according to Stockfish, a classification of "good" is intended behaviour here.
