### ISSUE TITLE
Lack of LICENSE

### ISSUE THREAD

**Issue by davidon-top** [WintrCat/freechess#8]
Hello,

I waned to make a desktop version of this in c++ with more engines and some other features but i noticed that there is no LICENSE file or mention of a license used  in this repo so i'm not sure if i can.
Could you please add a LICENSE file or some form of a license notice so that i know whether i can and under what license i can create the desktop version. btw you can use [this handy website](https://choosealicense.com/) to chose a license that fits your needs best

**Comment by WintrCat** [comment]
I added a license 👍
